name = "Better MC [FABRIC] - BMC2"
version = "v25"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "5f39fac57f550eba0156b65f72ce6cf7c31f77f6277510b42c89fc105fc9675e"

[versions]
fabric = "0.15.11"
minecraft = "1.20.1"
